# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170506_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatar/default.png', upload_to='avatar/'),
        ),
    ]
