# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 03:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=home.models.upload_location, width_field='width_field')),
                ('description', models.TextField(max_length=5000)),
                ('minimum_amount', models.FloatField()),
                ('maximum_amount', models.FloatField()),
                ('end_date', models.DateField()),
                ('complete_date', models.DateField(null=True)),
                ('pledged_amount', models.FloatField()),
                ('pledged_people_num', models.IntegerField()),
                ('status', models.CharField(choices=[('looking for funds', 'looking for funds'), ('pledge succeeded', 'pledge succeeded'), ('pledge failed', 'pledge failed'), ('completed', 'completed')], default='pending', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cate_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Categories')),
                ('uid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
