# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_picture/%y%m%d'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='pledged_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='pledged_people_num',
            field=models.IntegerField(default=0),
        ),
    ]
