# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170501_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.upload_location),
        ),
    ]
