# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170501_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_picture/%y%m%d'),
        ),
    ]
