# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170503_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcards',
            name='cnum',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='creditcards',
            name='exp_date',
            field=models.DateField(),
        ),
    ]
