# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170503_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcards',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='creditcards',
            name='last_name',
        ),
        migrations.AddField(
            model_name='creditcards',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
