# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170503_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcards',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
