# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_pledges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledges',
            name='pid',
            field=models.CharField(max_length=40),
        ),
    ]
