# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20170504_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledges',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='pending', max_length=40),
        ),
    ]
