# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledges',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Projects'),
        ),
    ]
