# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 02:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0016_auto_20170504_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='project_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
