# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20170505_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=home.models.upload_location, width_field='width_field'),
        ),
    ]
