# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_project_updates_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='star',
            field=models.IntegerField(choices=[(1, '\ue335'), (2, '\ue335\ue335'), (3, '\ue335\ue335\ue335'), (4, '\ue335\ue335\ue335\ue335'), (5, '\ue335\ue335\ue335\ue335\ue335')]),
        ),
    ]
