# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20170507_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='star',
            field=models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')]),
        ),
    ]
