# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_project_updates_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
